pipeline {
    agent {
        docker {
                    image 'gradle:jdk17-jammy'
                    args '-v /root/.gradle:/root/.gradle'
                }
    }

    stages {
        stage('Build') {
            steps {
                sh 'gradle clean'
            }
        }
        stage('Test') {
            steps {
                sh 'gradle build'
            }
        }
        stage('Deploy') {
            steps {
                sh 'gradle bootrun'
            }
        }
    }
}