pipeline {
    agent {
        docker {
                    image 'gradle:jdk17-jammy'
                    args '-v /root/.m2:/root/.m2'
                }
    }

    stages {
        stage('Build') {
            steps {
                sh 'gradle clean classes'
            }
        }
        stage('Test') {
            steps {
                sh 'gradle build'
            }
        }
        stage('Deploy') {
            steps {
                sh 'gradle bootjar'
                sh 'docker build -t spring-boot-docker .'
            }
        }
    }
}